### PR TITLE
fix: Handle array-type triggers in auto-responder (PR #669 follow-up)

### PR DESCRIPTION
**Pull request by Codename-11**
# Fix: Auto-Responder Array Trigger Support in Auto-Responder

**Branch:** `fix/auto-responder-array-trigger-handling`

## Issue

Auto-responder triggers with array-type patterns (introduced in PR #669) were causing `TypeError: triggerStr.trim is not a function` when executed.

## Root Cause

PR #669 added support for `trigger.trigger` to be either `string | string[]` in the TypeScript types, but the backend implementation only handled the string case. The `splitTriggerPatterns()` function attempted to call `.trim()` on arrays, causing the error.

**Why this was missed:** The type system allowed both formats, but runtime validation and processing logic was not updated to handle arrays alongside the existing comma-separated string format.

### 1. Array/String Pattern Handling (`meshtasticManager.ts:4347`)
```typescript
// Handle both string and array types for trigger.trigger
const patterns = Array.isArray(trigger.trigger)
  ? trigger.trigger
  : splitTriggerPatterns(trigger.trigger);
```

### 2. Environment Variable Handling (`meshtasticManager.ts:4589`)
```typescript
TRIGGER: Array.isArray(trigger.trigger) ? trigger.trigger.join(', ') : trigger.trigger,
MATCHED_PATTERN: matchedPattern || '',
```
Scripts now receive the matched pattern and proper TRIGGER string (even when source is array).

### 3. Input Validation (`server.ts:3237`)
```typescript
// Validate trigger is string or non-empty array
if (Array.isArray(trigger.trigger) && trigger.trigger.length === 0) {
  return res.status(400).json({ error: 'Trigger array cannot be empty' });
}
if (!Array.isArray(trigger.trigger) && typeof trigger.trigger !== 'string') {
  return res.status(400).json({ error: 'Trigger must be a string or array of strings' });
}
```

### 4. Startup Script Discovery (`server.ts:5194`)
Lists available scripts at server startup to aid debugging:
```
📜 Auto-responder scripts directory: /path/to/data/scripts
   Found 3 script(s): ai.py, PirateWeather.py, sunrise.py
```

### 5. Enhanced Error Messages
- Script path resolution shows resolved paths and existence check (debug level)
- Script not found errors show working directory and expected location
- Script execution start logged at info level

## Security Review

✅ **Script Path Validation:** Existing validation ensures paths start with `/data/scripts/` and contain no `..` traversal  
✅ **Input Validation:** Added checks for empty arrays and type validation  
✅ **No Code Injection:** Array elements are treated as strings, not executed code  
✅ **Environment Variables:** Arrays safely joined as comma-separated strings

## Edge Cases Handled

- Empty arrays → Validation error
- Non-string, non-array triggers → Validation error  
- Array elements processed identically to split comma-separated strings
- Mixed format backward compatibility maintained

## Testing

- ✅ Unit tests pass
- ✅ Manual testing with array triggers successful
- ✅ Manual testing with string triggers successful
- ✅ Script execution confirmed working

## Impact

- **Backward Compatible:** ✅ String patterns unchanged
- **New Feature:** ✅ Array patterns now functional  
- **Breaking Changes:** ❌ None
- **Database Changes:** ❌ None
- **Frontend Changes:** ❌ None

## Code Review Improvements (Commit 2)

Following code review feedback, additional improvements were made:

### 1. Fixed Script Test Endpoint (server.ts:4554) - CRITICAL
The `/api/scripts/test` endpoint was still calling `splitTriggerPatterns()` without checking for arrays, which would cause the same TypeError during testing.

**Fixed:** Now uses `normalizeTriggerPatterns()` to handle both formats.

### 2. DRY Refactoring - Extracted Shared Utility
Created `src/utils/autoResponderUtils.ts` with:
- `splitTriggerPatterns()` - Splits comma-separated trigger strings
- `normalizeTriggerPatterns()` - Handles both string and array formats

This eliminates ~80 lines of duplicate code between `meshtasticManager.ts` and `server.ts`.

### 3. Comprehensive Test Coverage
Added `src/utils/autoResponderUtils.test.ts` with 20 test cases covering:
- Simple and complex pattern splitting
- Array and string handling
- Edge cases (empty arrays, nested braces, malformed input)
- ✅ All tests passing

## Files Modified

- `src/server/meshtasticManager.ts` - Pattern handling, env vars, logging (uses shared utility)
- `src/server/server.ts` - Input validation, startup logging, test endpoint fix (uses shared utility)
- `src/utils/autoResponderUtils.ts` - **NEW**: Shared trigger pattern utilities
- `src/utils/autoResponderUtils.test.ts` - **NEW**: Comprehensive unit tests

### CODE REVIEW

**Comment by Codename-11** [comment]
Making suggested changes now 👍

**Comment by Codename-11** [comment]
> **Claude encountered an error** —— [View job](https://github.com/Yeraze/meshmonitor/actions/runs/19603094379)
> 
> I'll analyze this and get back to you.

Cancelled this run after ~45 minutes and re-ran - didn't want it to burn any more minutes for the repo 😯. Saw there's a few bug reports open related to the review workflow getting stuck at "Setting up Claude Code".
